### PR TITLE
Fix getting macOS name from installer path string

### LINKED ISSUE #82: Account for installer.app being staged in a different location.
If the installer.app is staged in a different directory (like /private/var) then in the jamfHelper dialogs the full path of the installer is displayed rather than just the "Install macOS High Sierra" part. To fix this you could change this line:
`macOSname=$(/bin/echo "$OSInstaller" | /usr/bin/sed 's/^\/Applications\/Install \(.*\)\.app$/\1/')`
to
`macOSname=$(echo ${OSInstaller##*/} | /usr/bin/sed -e 's/Install \(.*\).app/\1/')`

### PR DESCRIPTION
**Pull request by kenchan0130**
Fix #82

### CODE REVIEW

File: macOSUpgrade.sh [hunk 1]
```diff
@@ -110,8 +110,7 @@ userDialog="$9"
 if [[ ${userDialog:=0} != 1 ]]; then userDialog=0 ; fi
 
 ##Title of OS
-##Example: macOS High Sierra
```
Comment (kenchan0130) [inline macOSUpgrade.sh]: I think this is not input from jamf parameters. Therefore, I removed this example comment.

File: macOSUpgrade.sh [hunk 2]
```diff
@@ -110,8 +110,7 @@ userDialog="$9"
...
-macOSname=$(/bin/echo "$OSInstaller" | /usr/bin/sed 's/^\/Applications\/Install \(.*\)\.app$/\1/')
+macOSname=$(/bin/echo "$OSInstaller" | /usr/bin/sed -E 's/(.+)?Install(.+)\.app\/?/\2/' | /usr/bin/xargs)
```
Comment (kenchan0130) [inline macOSUpgrade.sh]: The `xargs` can trim unnecessary white spaces.
