### PR TITLE
When the user upgrade OS to macOS mojave, required disk space is 20GB

### LINKED ISSUE #117: macOS Mojave upgrade fails due to lack of space even though it passed the 15GB system check
Came across a Mac that had about 17GB of free space so it made it past the pre-check but once it began the actual in-place upgrade it fails to complete due to lack of storage space.

I removed a few GB to get to 21GB free and tried again. This time I was successful. To avoid this, I am suggesting to change the following parameter on https://github.com/kc9wwh/macOSUpgrade/blob/e193c61d83b51e1d0d89a6b93156e25f4b1d9a3c/macOSUpgrade.sh#L217, https://github.com/kc9wwh/macOSUpgrade/blob/e193c61d83b51e1d0d89a6b93156e25f4b1d9a3c/macOSUpgrade.sh#L226 and https://github.com/kc9wwh/macOSUpgrade/blob/e193c61d83b51e1d0d89a6b93156e25f4b1d9a3c/macOSUpgrade.sh#L377 are as so:

##Check if free space > 20GB

if [[ ${freeSpace%.*} -ge 20000000000 ]]; then

    /Library/Application\ Support/JAMF/bin/jamfHelper.app/Contents/MacOS/jamfHelper -windowType utility -title "$title" -icon "$icon" -heading "Requirements Not Met" -description "We were unable to prepare your computer for $macOSname. Please ensure you are connected to power and that you have at least 20GB of Free Space.

### PR DESCRIPTION
**Pull request by kenchan0130**
Fix #117 

## Why did I put a conditional branch
Since the disk space is not something that can be emptied so easily, I narrow down the conditions as much as possible.

### CODE REVIEW

File: macOSUpgrade.sh [hunk 1]
```diff
@@ -223,7 +223,10 @@ else
     freeSpace=$( /usr/sbin/diskutil info / | /usr/bin/grep "Free Space" | /usr/bin/awk '{print $6}' | /usr/bin/cut -c 2- )
 fi
 
-if [[ ${freeSpace%.*} -ge 15000000000 ]]; then
+if [[ ${freeSpace%.*} -ge 20000000000 ]] && [ "$osMajor" -gt 13 ]; then
+    spaceStatus="OK"
+    /bin/echo "Disk Check: OK - ${freeSpace%.*} Bytes Free Space Detected"
+elif [[ ${freeSpace%.*} -ge 15000000000 ]]; then
```
Comment (taniguti) [inline macOSUpgrade.sh]: I think we can make here simpler. 
Check target OS version, then set required free storage size. 
No need to use 'elif and no need take care about 15G or 20G later code at L.381.

```
if [ "$osMajor" -ge 14 ]; then 
    requiredDiskSpaceSize=20 
else
    requiredDiskSpaceSize=15
fi
if [ ${freeSpace%.*} -ge $(( requiredDiskSpaceSize * 1000 * 1000 * 1000 )) ] then
   spaceStatus=OK
  ...
else
  spaceStatus="ERROR"
 ...
fi
```

I think it is ok just "$freeSpace" instead of ${freeSpace%.*}.

Comment (kenchan0130) [reply macOSUpgrade.sh]: I changed this by https://github.com/kc9wwh/macOSUpgrade/pull/118/commits/617e9ea219711098e8564fe5a0360c4159424bfd.

**Comment by kenchan0130** [comment]
@taniguti PTAL

**Comment by kenchan0130** [comment]
Thank you for your review.
